### ISSUE TITLE
Think i used too much it and now return empty array

### ISSUE THREAD

**Issue by bdmariobd** [kyle-n/unofficial-amazon-search#17]
Is there a way to avoid it?

**Comment by kyle-n** [comment]
I have no knowledge of Amazon's rate-limiting systems. I'd advise waiting a while and seeing if they let you send requests again. Otherwise, not much you can do. Try to not hit their systems too much - it's Amazon, they know a thing or two about spammers and scraping.

Closing this since it is an issue with your application and not with this library.
